// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using memegenerator;

namespace memegenerator.Migrations
{
    [DbContext(typeof(MemeContext))]
    [Migration("20190327231759_AddedMemeSeedData")]
    partial class AddedMemeSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("memegenerator.Model.Meme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrentBottomText");

                    b.Property<string>("CurrentImage");

                    b.Property<string>("CurrentTopText");

                    b.HasKey("Id");

                    b.ToTable("Memes");

                    b.HasData(
                        new { Id = 1, CurrentBottomText = "MASTER CODING", CurrentImage = "/images/LordOfRings.png", CurrentTopText = "ONE DOES NOT SIMPLY" },
                        new { Id = 2, CurrentBottomText = "DOES THIS ERROR MEAN", CurrentImage = "/images/Picard.png", CurrentTopText = "WHAT THE HECK" },
                        new { Id = 3, CurrentBottomText = "ALL I HAD TO DO IS RESTART VISUAL STUDIO?", CurrentImage = "/images/SuspectBaby.png", CurrentTopText = "SO YOU'RE TELLIN ME" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
